### ISSUE TITLE
resize shiny glide 

### ISSUE THREAD

**Issue by abeeCrombie** [juba/shinyglide#12]
I am trying to embed a highchart object into a shiny glide but I cannot figure out how to resize the glide object to make the highcharter object larger.

I have been able to adjust `modalDialog` height but cannot adjust width. And it looks like the highchart object is cut out before the adjust height was hit

any ideas

<img width="706" alt="shinly_glide" src="https://user-images.githubusercontent.com/20419614/92168625-b27e6b80-ee08-11ea-94c8-8bfff0205f81.png">

**Comment by juba** [comment]
Hi, would you have a reproducible example ?

**Comment by juba** [comment]
Closing for now.
