### ISSUE TITLE
Infobox/valuebox

### ISSUE THREAD

**Issue by BerramouMohamed** [juba/shinyglide#14]
I tried to use infobox and value box inside glide > screen but  it doesn't keep the style of boxex
![Screenshot_2](https://user-images.githubusercontent.com/48687862/97967464-88700800-1dbd-11eb-92d7-7735ea24046c.png)
.

**Comment by juba** [comment]
Hi,

Would it be possible for you to give a reproducible example ?

**Comment by BerramouMohamed** [comment]
Hi, Sorry my bad, the problem came from shiny navbarpage, by the way thank you for this awesome package :)

**Comment by juba** [comment]
You're welcome, glad it fixed by itself !
