### ISSUE TITLE
Provide shiny input IDs for first and lastbutton

### ISSUE THREAD

**Issue by JosiahParry** [juba/shinyglide#16]
I'd like to be able to know if the modal pop up has been closed. It appears that there is no way to provide an input ID of some sort to the lastbutton. I'd like this to be able to submit values from the pop up after clicking submit.

**Comment by juba** [comment]
I'm not sure what precisely your request is here. Do you want to just add an `id` argument to your last button ? I think it is possible with the `lastButton` function :

```r
lastButton(id = "foo")
```
