### ISSUE TITLE
gliderControls() missing default arguments

### ISSUE THREAD

**Issue by JosiahParry** [juba/shinyglide#17]
In attempting to modify _only_ the lastButton, I am using `gliderControls()`. The function, however, fails indicating `Error in dots_list(...) : argument "next_content" is missing, with no default`.

In my server I have the below based on the vignette. 

```
  controls <- glideControls(
    list(
      lastButton(class = "btn btn-success",
                 `data-dismiss` = "modal",
                 "Done")
    ))
```

**Comment by JosiahParry** [comment]
Update: specified the argument by name and it forced previous content. Perhaps the function can look like 

```
glideControl <- function(previous_content = prevButton("Back"), next_content = nextButton("Next")) {

...

}

**Comment by juba** [comment]
Yes, you're right, it's better to have default values in `glideControls` so that you can redefine only one if needed.

This is fixed in the development version.
