### ISSUE TITLE
Documentation Request: where to place glideControls

### ISSUE THREAD

**Issue by JosiahParry** [juba/shinyglide#18]
The documentation for glideControls does not specify where the function is to be used. From [this article](https://juba.github.io/shinyglide/articles/c_custom_controls.html) it appears that the output ought to be saved to a variable outside of ui and server sections. Can the documentation be improved to provide more clarity?

**Comment by juba** [comment]
There is no obligation to use `glideControls` in a variable outside of `ui`, the fact that I did it this way in the examples was just for readability. I modified the first example by using it directly in `ui` declaration. Maybe it's clearer this way ?
