### ISSUE TITLE
"Refresh" or clear output of current screen when you navigate away

### ISSUE THREAD

**Issue by latlio** [juba/shinyglide#20]
Hi, recently found your package, and thanks for developing it!

I was wondering if it's possible to "reset" inputs/outputs when you navigate away a screen. 

For instance, if you have (using pseudocode here):

- selectInput on Screen 1, buttons: Next
- random HTML text on Screen 2, buttons: Previous, Next
- print(input) on Screen 3, buttons: Previous, Return to first screen (<<)

How do you reset selectInput and print(input) on Screens 1 and 3 respectively when you navigate to away from those screens?

**Comment by juba** [comment]
Hi,

I think this is outside the scope of `shinyglide` right now, you would have to implement it in JavaScript. The simpler way I can think of would be to registrer an handler for one of the Glide.js events :

https://glidejs.com/docs/events/

And then, in the handler, use `Shiny.setInputValue()` to reset your inputs : 

https://shiny.rstudio.com/articles/communicating-with-js.html

**Comment by juba** [comment]
For information there is now a way to get pack the current slide as a Shiny input. See #22.
