### ISSUE TITLE
Does next_condition support ns() within shiny modules

### ISSUE THREAD

**Issue by latlio** [juba/shinyglide#24]
Modularizing your minimal example that I found [here](https://juba.github.io/shinyglide/articles/b_conditionals.html)

The next button remains disabled even though the conditional is fulfilled. In `conditionalPanel`, there is an explicit `ns` argument included. Is there support for this within `shinyglide`?

```
test_mod_ui <- function(id) {
  ns <- NS(id)
  numericInput(ns("n"), "n :", value = 0)
  
  plotOutput(ns("plot"))
}

test_mod_server <- function(input, output, session) {
  output$plot <- renderPlot({
    hist(rnorm(input$n), main = paste("n =", input$n))
  })
}

ui <- fluidPage(
  glide(
    screen(
      next_condition = "input.n > 0",
      
      p("Please choose a value for n :"),
      test_mod_ui("mod1")
    ),
    screen(
      p("Done."),
    )
  )
)

server <- function(input, output, session) {
  callModule(test_mod_server, "mod1")
            
}

shinyApp(ui, server)
```

**Comment by juba** [comment]
This is not specific to `shinyglide`, but for this to work you have to add the module name to your element id in your condition (and you can't use the dot notation because of the presence of an hyphen) : 

```
next_condition = "input['mod1-n'] > 0"
```

See also here : https://stackoverflow.com/a/39110211
