### ISSUE TITLE
glide isn't properly resized when a vertical scrollbar appears

### ISSUE THREAD

**Issue by ismirsehregal** [juba/shinyglide#30]
Using shinyglide 0.1.3 (latest CRAN) the glide isn't properly resized when a vertical scrollbar appears.

Please see the following example and note the upper right part of the app (the right side of the upper `wellPanel` gets cut-off):

```
library(shiny)
library(shinyglide)
library(datasets)

ui <- fluidPage(
  titlePanel("Hello Shiny!"),
  sidebarLayout(
    sidebarPanel(
      radioButtons("test", "test", choices = c("show", "hide")),
      sliderInput("obs",
                  "Number of observations:",
                  min = 0,
                  max = 1000,
                  value = 500)
    ),
    mainPanel(
      glide(screen(wellPanel("First screen.")), screen(wellPanel("Second screen."))),
      p(),
      wellPanel("Another wellPanel."),
      conditionalPanel("input.test === 'show'",
                       tableOutput("iris_out"))
    )
  )
)

server <- function(input, output) {
  output$iris_out <- renderTable(iris)
}

shinyApp(ui, server)
```
![Animation](https://user-images.githubusercontent.com/36849480/157007213-15a66e1b-6a61-4e0f-80c1-ae7758a2aa21.gif)

**Comment by juba** [comment]
Indeed, window resize was handled but not parent element resize. I think this should now be fixed in the development version, but let me know if it is not the case.

Thanks for the detailed report.

**Comment by ismirsehregal** [comment]
@juba thanks for the swift update! It works fine now.
