### ISSUE TITLE
Next button no longer functional after re-rendering glide

### ISSUE THREAD

**Issue by ismirsehregal** [juba/shinyglide#42]
Coming from [here](https://stackoverflow.com/questions/75875329/render-n-screen-for-shinyglide-based-on-a-numericinput):

Once the number of screens is increased, the next button is no longer functional (using latest CRAN version):

![image](https://user-images.githubusercontent.com/36849480/228563695-1048094d-f23d-484a-918f-a0550d740e45.png)

[This](https://github.com/juba/shinyglide/issues/38) seems to be related.

```
library(shiny)
library(shinyglide)

ui <- fluidPage(
  numericInput(
    inputId = "NbScreen",
    label = "Number of screens:",
    value = 3,
    min = 1,
    max = 100
  ),
  uiOutput("glideUI")
)

server <- function(input, output, session) {
  output$glideUI <- renderUI({
    glide(
      lapply(seq_len(input$NbScreen), function(i) {
        screen(p(paste("screen", i)))
      })
    )
  })
  outputOptions(output, "glideUI", suspendWhenHidden = FALSE)
}

shinyApp(ui, server)
```

**Comment by juba** [comment]
Did you try with the development version ?

**Comment by ismirsehregal** [comment]
@juba this is indeed working fine using the dev version, thank you!
