### ISSUE TITLE
Fix javascript errors on init ?

### ISSUE THREAD

**Issue by bthieurmel** [juba/shinyglide#43]
Hi,

Can be a good idea to fix all javascript errors rendering in Web Developpement console (F12).

![image](https://github.com/juba/shinyglide/assets/8750326/659a711c-0ee8-4fc9-848c-740934a6e536)

Can be reproduce using simply ``screenOutput`` example. 

I think we just need to add some js check before some called / action like  !== undefined or !== null

Cheers

**Comment by juba** [comment]
Hi,

I think this should now be fixed in the development version. Thanks for taking the time to report the issue.
