### ISSUE TITLE
Error when running on Shiny Server

### ISSUE THREAD

**Issue by HashimNV** [juba/shinyglide#48]
I'm trying to run my application on Shiny Server. Everything works well except this package and I get the following error:

Uncaught TypeError: MutationObserver.observe: Argument 1 is not an object.
    <anonymous> https://shiny.abc.com/hnaveed/xyz_Dashboard/shinyglide-0.1/shinyglide.js:2
    <anonymous> https://shiny.abc.com/hnaveed/xyz_Dashboard/shinyglide-0.1/shinyglide.js:2
    <anonymous> https://shiny.abc.com/hnaveed/xyz_Dashboard/shinyglide-0.1/shinyglide.js:2

Uncaught TypeError: window.Shiny.shinyapp is undefined
    update_conditions https://shiny.abc.com/hnaveed/xyz_Dashboard/shinyglide-0.1/shinyglide.js:2
    update_controls https://shiny.abc.com/hnaveed/xyz_Dashboard/shinyglide-0.1/shinyglide.js:2
    init https://shiny.abc.com/hnaveed/xyz_Dashboard/shinyglide-0.1/shinyglide.js:2
    mt https://shiny.abc.com/hnaveed/xyz_Dashboard/shinyglide-0.1/shinyglide.js:2
    yt https://shiny.abc.com/hnaveed/xyz_Dashboard/shinyglide-0.1/shinyglide.js:2
    jQuery 2
    yt https://shiny.abc.com/hnaveed/xyz_Dashboard/shinyglide-0.1/shinyglide.js:2
    <anonymous> https://shiny.abc.com/hnaveed/xyz_Dashboard/shinyglide-0.1/shinyglide.js:2**

When I run the app with the shinyglide package on localhost, it works well. Only when it is run on Shiny Server does it throw these errors.

What do you think could be an issue?

Thanks in advance :)

**Comment by juba** [comment]
Hi, do you know what versions of shiny and shinyglide are running on localhost and on your server ?

**Comment by HashimNV** [comment]
Shiny version: 1.8.0
shinyglide version: 0.1.4

**Comment by juba** [comment]
It is the same version both on localhost and on the server ?

**Comment by HashimNV** [comment]
I believe so as I'm not changing anything in the script.
How do I check on the server?

**Comment by juba** [comment]
Hmm if you have access to the server you could just check what shiny version is installed there, otherwise maybe create a small shiny app that just displays it ?

There are more informations here I think : https://stackoverflow.com/questions/25992642/rstudio-shiny-how-can-i-display-the-version-of-the-shiny-server-in-the-shiny-pag

**Comment by juba** [comment]
Another thing you can check, when your app is open in your browser, is to open the developer tools, go to console and type "window.Shiny".

![image](https://github.com/juba/shinyglide/assets/245367/710c238e-ba08-4aa5-9568-0cfae83c0930)

**Comment by HashimNV** [comment]
<img width="520" alt="2024-01-29 14_09_19-Dashboard" src="https://github.com/juba/shinyglide/assets/23610622/b9544536-4170-44a8-9c57-7db84d149fd0">

**Comment by juba** [comment]
Strange, I can't reproduce this problem with Shiny 1.8.0... Are you using the latest Github development version ?

**Comment by HashimNV** [comment]
The issue is resolved. There was an issue on the server side. It worked well when I fixed that.
Thanks for the help and the package.
